// Copyright (c) Csaba Molnar & Daniel Butum. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Internationalization/Text.h"

// Define string tables
#define STRING_TABLE_UI "UI"
#define STRING_TABLE_UI_TEXT TEXT(STRING_TABLE_UI)

#define STRING_TABLE_INTERACTION "Interaction"
#define STRING_TABLE_INTERACTION_TEXT TEXT(STRING_TABLE_INTERACTION)

#define STRING_TABLE_DIALOGUE "Dialogue"
#define STRING_TABLE_DIALOGUE_TEXT TEXT(STRING_TABLE_DIALOGUE)

#define STRING_TABLE_ITEMS "Items"
#define STRING_TABLE_ITEMS_TEXT TEXT(STRING_TABLE_ITEMS)

#define STRING_TABLE_SPELLS "Spells"
#define STRING_TABLE_SPELLS_TEXT TEXT(STRING_TABLE_SPELLS)

#define STRING_TABLE_AREAS "Areas"
#define STRING_TABLE_AREAS_TEXT TEXT(STRING_TABLE_AREAS)

#define STRING_TABLE_ENEMIES "Enemies"
#define STRING_TABLE_ENEMIES_TEXT TEXT(STRING_TABLE_ENEMIES)

#define STRING_TABLE_EPISODES "Episodes"
#define STRING_TABLE_EPISODES_TEXT TEXT(STRING_TABLE_EPISODES)

#define STRING_TABLE_FLOATING_ENEMY_AND_NPC_LINES "FloatingEnemyAndNPCLines"
#define STRING_TABLE_FLOATING_ENEMY_AND_NPC_LINES_TEXT TEXT(STRING_TABLE_FLOATING_ENEMY_AND_NPC_LINES)

#define STRING_TABLE_CREDITS "Credits"
#define STRING_TABLE_CREDITS_TEXT TEXT(STRING_TABLE_CREDITS)


// Define helpers for FText::FromStringTable
#define FROM_STRING_TABLE(InTableId, InKey) FText::FromStringTable(TEXT(InTableId), TEXT(InKey))

#define FROM_STRING_TABLE_UI(InKey) FROM_STRING_TABLE(STRING_TABLE_UI, InKey)
#define FROM_STRING_TABLE_DIALOGUE(InKey) FROM_STRING_TABLE(STRING_TABLE_DIALOGUE, InKey)
#define FROM_STRING_TABLE_EPISODES(InKey) FROM_STRING_TABLE(STRING_TABLE_EPISODES, InKey)
#define FROM_STRING_TABLE_INTERACTION(InKey) FROM_STRING_TABLE(STRING_TABLE_INTERACTION, InKey)
